# This overlay patches in KubeRay operator configuration
# necessary for KubeRay single namespace support.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
patches:
- path: patch-cluster-role.json
  target:
    kind: ClusterRole
- path: patch-cluster-role-binding.json
  target:
    kind: ClusterRoleBinding
- path: patch-deployment.json
  target:
    kind: Deployment
    name: kuberay-operator
- path: patch-others.json
  target:
    version: v1
